"""Update: table:user 添加nickname字段，设置部分字段不允许为null

Revision ID: a7a11b292afe
Revises: 4e472ff5e03b
Create Date: 2022-03-01 13:50:49.903968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7a11b292afe'
down_revision = '4e472ff5e03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=255), nullable=False))
    op.alter_column('user', 'account',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'account',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
